pod 'Parse-iOS-SDK', '~>1.2.19'
pod 'UIImage+Additions', '~>1.1.0'
pod 'SVProgressHUD', '~>1.0.0'
pod 'SSKeychain', '~>1.2.2'
pod 'Shimmer', '~>1.0.1'
pod 'AHKActionSheet', '~>0.4.2'
pod 'CrashlyticsFramework', '~>2.2'
